// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlbouluqtdhoatmkrfsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sYm91bHVxdGRob2F0bWtyZnNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzYwMDEsImV4cCI6MjA2OTc1MjAwMX0.Zh_gPN9mehbO7NO7PucqALrDt4-xwVCCXJlmIiYBw9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});