// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpnyzqiqqgypvwuxfrnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impwbnl6cWlxcWd5cHZ3dXhmcm5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyOTEwNjIsImV4cCI6MjA3MDg2NzA2Mn0.hmhJeogacviamkCLD9tL7bgzpsEdZqUXoJhnv5JJEdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});